[workspace]

members = [
    "canister",
    "examples/common",
    "examples/rust",
    "types",
]

[patch.crates-io]
bitcoin = { git = "https://github.com/Octan-Finance/rust-litecoin", branch = "litecoin-compatible" }